model_run: effdet_d2_wd0.005_2026-02-16_16.21.05
device: cuda:0
rank: 0
local_rank: 0
world_size: 2
is_main: true
images:
  resize: 1024
metadata:
  norm_path: metadata/dataset_norm.json
  norm:
    means:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  target_mapping_path: metadata/target_mapping.json
  target_mapping: null
logging_level: INFO
directories:
  image_dir: data/raw
  train_annotations_file: data/train_labels.json
  val_annotations_file: data/val_labels.json
  output_dir: outputs
  checkpoint_dir: model_checkpoints
  log_dir: logs/run_logs
training:
  epochs: 50
  sanity_check: true
model:
  backbone_out_channels: 256
  num_classes: 3
  detections_per_img: 500
effdet:
  architecture: tf_efficientdet_d2
  pretrained: true
  score_threshold: 0.01
  nms_iou_threshold: 0.5
  max_detections_per_img: 100
optimizer:
  name: AdamW
  weight_decay: 0.0
  original_weight_decay: 0.005
  filter_bias_and_bn: true
  ema: true
  ema_decay: 0.9
  optimizer_params:
    lr: 0.0003
    momentum: 0.9
    nesterov: true
    dampening: 0.0
    alpha: 0.99
    gamma: 0.99
    etas:
    - 0.5
    - 1.2
    betas:
    - 0.9
    - 0.999
    rho: 0.9
    amsgrad: false
    foreach: null
scheduler:
  name: ExponentialLR
  gamma: 0.99
  step_size: 1.0e-05
  T_max: 5
  eta_min: 0.0
  T_0: null
  T_mult: 1
  last_epoch: -1
batch_size: 6
num_workers: 6
